In [1]:
#Import Necessary Library's
import pandas as pd
import json
from pathlib import Path

In [5]:
#Import Data
data_folder = Path("./Data/")
GDPData = data_folder / "GDPfinal.json"

# read in json file of GDP data 
data_df = pd.read_json(GDPData)
data_df2 = data_df.drop(data_df.columns.difference(["Country", "Population Rank","Growth Rate", "World Percentage", "GDP(IMF)", "GDP(UN)", "GDP Per Capita"]), 1)
data_df2.set_index("Country", inplace = True)
data_df2

                Population Rank Growth Rate World Percentage GDP Per Capita
Country
Spain                      30.0       0.04%            0.60%     $32,019.83
Cyprus                    158.0       0.73%            0.02%     $21,822.84
Bahrain                   152.0       3.68%            0.02%     $23,923.13
Bhutan                    165.0       1.12%            0.01%      $3,808.93
Singapore                 114.0       0.79%            0.08%     $66,983.26
...                         ...         ...              ...            ...
Venezuela                  50.0      -0.28%            0.36%       $2,465.4
Brazil                      6.0       0.72%            2.73%      $9,703.17
United Kingdom             21.0       0.53%            0.87%     $43,117.57
Japan                      11.0      -0.30%            1.62%     $43,450.14
Canada                     39.0       0.89%            0.48%     $48,552.87

[184 rows x 4 columns]